version: "3.7"
services:
  mypython:
    container_name: beta_network
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      DISPLAY: unix$DISPLAY
